export const dummyData = [
  {
    id: 1,
    category: '공지',
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '3.6k',
    comment: '21',
    vote: '58',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 2,
    category: '일상',
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 3,
    category: '정보',
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 4,
    category: '유머',
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
];

export const dummyData2 = [
  {
    id: 1,
    category: '공지',
    selected: false,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '3.6k',
    comment: '21',
    vote: '58',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 2,
    category: '국어',
    selected: false,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 3,
    category: '영어',
    selected: true,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 4,
    category: '수학',
    selected: false,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
];
