// export const dummyData = [
//   {
//     data: [
//       {
//         freeId: 1,
//         category: '공지',
//         username: '닉네임',
//         userimg: '프로필이미지url',
//         title: '게시물 제목',
//         content: '게시물 내용',
//         viewCount: 360,
//         voteCount: 58,
//         createdAt: '1시간 전',
//         modifiedAt: '게시글수정시간',
//         commentsListNum: 21,
//       },
//     ],
//     pageInfo: {
//       page: 1,
//       size: 15,
//       totalElements: 4,
//       totalPages: 1,
//     },
//   },
//   {
//     data: [
//       {
//         freeId: 2,
//         category: '일상',
//         username: '닉네임',
//         userimg: '프로필이미지url',
//         title: '게시물 제목',
//         content: '게시물 내용',
//         viewCount: 36,
//         voteCount: 5,
//         createdAt: '1시간 전',
//         modifiedAt: '게시글수정시간',
//         commentsListNum: 0,
//       },
//     ],
//     pageInfo: {
//       page: 1,
//       size: 15,
//       totalElements: 4,
//       totalPages: 1,
//     },
//   },
//   {
//     data: [
//       {
//         freeId: 3,
//         category: '정보',
//         username: '닉네임',
//         userimg: '프로필이미지url',
//         title: '게시물 제목',
//         content: '게시물 내용',
//         viewCount: 36,
//         voteCount: 5,
//         createdAt: '1시간 전',
//         modifiedAt: '게시글수정시간',
//         commentsListNum: 0,
//       },
//     ],
//     pageInfo: {
//       page: 1,
//       size: 15,
//       totalElements: 4,
//       totalPages: 1,
//     },
//   },
//   {
//     data: [
//       {
//         freeId: 4,
//         category: '유머',
//         username: '닉네임',
//         userimg: '프로필이미지url',
//         title: '게시물 제목',
//         content: '게시물 내용',
//         viewCount: 36,
//         voteCount: 5,
//         createdAt: '1시간 전',
//         modifiedAt: '게시글수정시간',
//         commentsListNum: 0,
//       },
//     ],
//     pageInfo: {
//       page: 1,
//       size: 15,
//       totalElements: 4,
//       totalPages: 1,
//     },
//   },
// ];

export const dummyData2 = [
  {
    id: 1,
    category: '공지',
    selected: false,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '3.6k',
    comment: '21',
    vote: '58',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 2,
    category: '국어',
    selected: false,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 3,
    category: '영어',
    selected: true,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
  {
    id: 4,
    category: '수학',
    selected: false,
    username: '닉네임',
    userimg: '프로필이미지url',
    title: '게시물 제목',
    content: '게시물 내용',
    view: '36',
    comment: '2',
    vote: '0',
    createdAt: '1시간 전',
    updatedAt: '게시글수정시간',
  },
];
